name: Update badges

on:
  workflow_dispatch: # run manually
  schedule:
    # Runs at 8am UTC on the 15th of each month
    - cron: '0 08 15 * *'
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: DeBoX85/badge-readme@main
        with:
          CREDLY_SORT: RECENT
          CREDLY_USER: denis-bogunic
          BADGE_SIZE: 150 # optional, 110x110 default
          NUMBER_LAST_BADGES: 14 # optional, will show the 48 in the first page
