name: Update badges

on:
  schedule:
    # Runs at 2am UTC
    - cron: "20 14 * * *"
  workflow_dispatch: # Enables manual triggering

jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: DeBoX85/DeboX85@main
        with:       
          CREDLY_USER: <denis-bogunic> # optional, but default will use the same from github
